# NYC Taxi data in Winter and Summer

Refer to the [Data dictionary](https://www1.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf) to learn more about the columns that have been provided.

In [1]:
#Install the pandas library
#!pip install pandas

Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.10/site-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import pandas as pd

path = '../../data/taxi.csv'

#Load the csv file into a dataframe
df = pd.read_csv(path)

#Print the dataframe
print(df)
df.head(20)

     VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         2.0  2019-07-15 16:27:53   2019-07-15 16:44:21              3.0
1         2.0  2019-07-17 20:26:35   2019-07-17 20:40:09              6.0
2         2.0  2019-07-06 16:01:08   2019-07-06 16:10:25              1.0
3         1.0  2019-07-18 22:32:23   2019-07-18 22:35:08              1.0
4         2.0  2019-07-19 14:54:29   2019-07-19 15:19:08              1.0
..        ...                  ...                   ...              ...
195       2.0  2019-01-18 08:42:15   2019-01-18 08:56:57              1.0
196       1.0  2019-01-19 04:34:45   2019-01-19 04:43:44              1.0
197       2.0  2019-01-05 10:37:39   2019-01-05 10:42:03              1.0
198       2.0  2019-01-23 10:36:29   2019-01-23 10:44:34              2.0
199       2.0  2019-01-30 06:55:58   2019-01-30 07:07:02              5.0

     trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0             2.02         1.0                  N           186           233
1             1.59         1.0                  N           141           161
2             1.69         1.0                  N           246           249
3             0.90         1.0                  N           229           141
4             4.79         1.0                  N           237           107
..             ...         ...                ...           ...           ...
195           1.18         1.0                  N            43           237
196           2.30         1.0                  N           148           234
197           0.83         1.0                  N           237           263
198           1.12         1.0                  N           144           113
199           2.41         1.0                  N           209           107

     payment_type  fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0             1.0         12.0    1.0      0.5        4.08           0.0
1             2.0         10.0    0.5      0.5        0.00           0.0
2             2.0          8.5    0.0      0.5        0.00           0.0
3             1.0          4.5    3.0      0.5        1.65           0.0
4             1.0         19.5    0.0      0.5        5.70           0.0
..            ...          ...    ...      ...         ...           ...
195           1.0         10.0    0.0      0.5        2.16           0.0
196           1.0          9.5    0.5      0.5        2.15           0.0
197           1.0          5.0    0.0      0.5        1.16           0.0
198           2.0          7.0    0.0      0.5        0.00           0.0
199           1.0         10.5    0.0      0.5        1.00           0.0

     improvement_surcharge  total_amount  congestion_surcharge
0                      0.3         20.38                   2.5
1                      0.3         13.80                   2.5
2                      0.3         11.80                   2.5
3                      0.3          9.95                   2.5
4                      0.3         28.50                   2.5
..                     ...           ...                   ...
195                    0.3         12.96                   0.0
196                    0.3         12.95                   0.0
197                    0.3          6.96                   0.0
198                    0.3          7.80                   0.0
199                    0.3         12.30                   0.0

[200 rows x 18 columns]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2.0,2019-07-15 16:27:53,2019-07-15 16:44:21,3.0,2.02,1.0,N,186,233,1.0,12.0,1.0,0.5,4.08,0.00,0.3,20.38,2.5
1,2.0,2019-07-17 20:26:35,2019-07-17 20:40:09,6.0,1.59,1.0,N,141,161,2.0,10.0,0.5,0.5,0.00,0.00,0.3,13.80,2.5
2,2.0,2019-07-06 16:01:08,2019-07-06 16:10:25,1.0,1.69,1.0,N,246,249,2.0,8.5,0.0,0.5,0.00,0.00,0.3,11.80,2.5
3,1.0,2019-07-18 22:32:23,2019-07-18 22:35:08,1.0,0.90,1.0,N,229,141,1.0,4.5,3.0,0.5,1.65,0.00,0.3,9.95,2.5
4,2.0,2019-07-19 14:54:29,2019-07-19 15:19:08,1.0,4.79,1.0,N,237,107,1.0,19.5,0.0,0.5,5.70,0.00,0.3,28.50,2.5
5,2.0,2019-07-28 11:38:08,2019-07-28 11:53:56,1.0,7.60,1.0,N,262,138,1.0,23.0,0.0,0.5,4.86,6.12,0.3,37.28,2.5
6,2.0,2019-07-18 07:15:25,2019-07-18 07:28:23,1.0,2.76,1.0,N,137,236,1.0,11.0,0.0,0.5,2.14,0.00,0.3,16.44,2.5
7,2.0,2019-07-02 21:13:44,2019-07-02 21:21:04,1.0,0.71,1.0,N,170,164,2.0,6.5,0.5,0.5,0.00,0.00,0.3,10.30,2.5
8,2.0,2019-07-12 09:58:59,2019-07-12 10:18:01,1.0,2.15,1.0,N,113,100,1.0,13.0,0.0,0.5,2.50,0.00,0.3,18.80,2.5
9,2.0,2019-07-23 10:05:02,2019-07-23 10:16:42,1.0,1.23,1.0,N,100,137,2.0,9.0,0.0,0.5,0.00,0.00,0.3,12.30,2.5
10,2.0,2019-07-31 22:26:26,2019-07-31 22:31:11,1.0,0.84,1.0,N,263,262,1.0,5.5,0.5,0.5,1.50,0.00,0.3,10.80,2.5
11,2.0,2019-07-01 22:49:58,2019-07-01 22:58:47,1.0,1.45,1.0,N,230,233,1.0,7.5,0.5,0.5,2.26,0.00,0.3,13.56,2.5
12,1.0,2019-07-08 07:32:02,2019-07-08 07:46:11,1.0,2.20,1.0,N,158,170,1.0,11.0,2.5,0.5,2.85,0.00,0.3,17.15,2.5
13,2.0,2019-07-17 05:57:12,2019-07-17 06:08:41,1.0,3.80,1.0,N,177,71,2.0,13.0,0.0,0.5,0.00,0.00,0.3,13.80,0.0
14,2.0,2019-07-24 08:25:02,2019-07-24 08:29:11,1.0,0.68,1.0,N,239,142,2.0,5.0,0.0,0.5,0.00,0.00,0.3,8.30,2.5
15,2.0,2019-07-13 23:53:53,2019-07-14 00:01:07,2.0,2.08,1.0,N,229,263,1.0,8.0,0.5,0.5,3.54,0.00,0.3,15.34,2.5
16,2.0,2019-07-05 06:52:39,2019-07-05 07:08:22,1.0,8.89,1.0,N,236,138,1.0,25.0,0.0,0.5,10.33,6.12,0.3,44.75,2.5
17,1.0,2019-07-25 15:29:43,2019-07-25 15:32:57,1.0,0.70,1.0,N,4,224,1.0,4.5,2.5,0.5,1.55,0.00,0.3,9.35,2.5
18,2.0,2019-07-22 09:28:20,2019-07-22 09:38:56,1.0,4.44,1.0,N,137,88,2.0,14.5,0.0,0.5,0.00,0.00,0.3,17.80,2.5
19,2.0,2019-07-24 03:32:07,2019-07-24 03:46:39,1.0,3.88,1.0,N,148,17,2.0,14.5,0.5,0.5,0.00,0.00,0.3,18.30,2.5

## Conclusions
- From the dataset: We have info on the time of the taxi trip, and the tips given to taxi drivers. As such, the data in the dataset can answer this question.
- This dataset is from 2019. The NYC Open Data catalog has Yellow Taxi Data across multiple years from approximately 2012-2022, so we can use those additional datasets to gleam more information.

#### Questions
1. Can we clearly define the time period for winter and summer in NYC? 
2. Can we define the scope of the time period (years) for this study?
3. Are there any taxi information that we should discard because of exceptions or edge cases?
4. Is the data of acceptable quality and does it account for all Yellow Taxis?